"""empty message

Revision ID: 304639a964f9
Revises: 
Create Date: 2024-05-26 00:45:40.320417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304639a964f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('api_id')

    # ### end Alembic commands ###
